version: '3'

services:
  bot:
    build: .
    command: python3 bot.py
    restart: always
    depends_on:
      - django
  web:
    build: .
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8080"
    container_name: chatgptbot
    volumes:
      - .:/chatgptbot
    ports:
      - "8000:8000"
