version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-lgxq)18p&le-*@4neeq@qmyr_a3pqgksh=p8p2#z=oq(d#^1$0

  bot:
    build: .
    ports:
      - "8443:8443"
    environment:
      - TELEGRAM_BOT_TOKEN=5601393100:AAGdAkp9VY_PZJIYtmlV-M9X22Eu51qvh00
